SELECT * FROM customer;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) as revenue_generated FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id , purchase_amount FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount::numeric),2) as average_purchase_amount FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type 

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and 
-- non subscribers
SELECT subscription_status,AVG(purchase_amount) as average_purchase_amount,SUM(purchase_amount) as 
total_purchase_amount FROM customer
GROUP BY subscription_status
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased , ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment

with customer_type as (
select customer_id,previous_purchases, 
case
when previous_purchases = 1 then 'new'
when previous_purchases between 1 and 10 then 'returning'
else 'loyal' end as customer_segment
from customer
)
select customer_segment,count(customer_segment) from customer_type
group by customer_segment